// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PharmacyApp.Infrastructure.Data;

#nullable disable

namespace PharmacyApp.Infrastructure.Migrations
{
    [DbContext(typeof(PharmacyAppDbContext))]
    [Migration("20260330215939_MakeOrderRowVersionNullable")]
    partial class MakeOrderRowVersionNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Pharmacist",
                            NormalizedName = "PHARMACIST"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.Bonus.BonusAccountModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BonusAccounts");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.Bonus.BonusSettingsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EarningRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsEarningEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRedemptionEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxRedeemPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("MinOrderAmountToEarn")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BonusSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EarningRate = 1m,
                            IsEarningEnabled = true,
                            IsRedemptionEnabled = true,
                            MaxRedeemPercent = 100m,
                            MinOrderAmountToEarn = 0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.Bonus.BonusTransactionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BonusAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Points")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BonusAccountId");

                    b.HasIndex("OrderId");

                    b.ToTable("BonusTransactions");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.CartItemModel", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PriceAtAdd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("CartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.CategoryModel", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "Essential vitamins and dietary supplements for your health",
                            CategoryName = "Vitamins & Supplements"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "Over-the-counter pain medications and relief products",
                            CategoryName = "Pain Relief"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDescription = "Medications and remedies for cold and flu symptoms",
                            CategoryName = "Cold & Flu"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryDescription = "First aid supplies and emergency medical equipment",
                            CategoryName = "First Aid"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryDescription = "Dermatological products and skin treatment solutions",
                            CategoryName = "Skincare"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryDescription = "Products for digestive system support and health",
                            CategoryName = "Digestive Health"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryDescription = "Healthcare products for infants and toddlers",
                            CategoryName = "Baby Care"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryDescription = "Blood pressure monitors, thermometers, and other medical devices",
                            CategoryName = "Medical Devices"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryDescription = "Eye drops, contact lens solutions, and vision care products",
                            CategoryName = "Eye Care"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryDescription = "Dental hygiene and oral health products",
                            CategoryName = "Oral Care"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryDescription = "Personal hygiene and grooming products",
                            CategoryName = "Personal Care"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryDescription = "Health products specifically for women",
                            CategoryName = "Women's Health"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryDescription = "Health products specifically for men",
                            CategoryName = "Men's Health"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryDescription = "Products for diabetes management and monitoring",
                            CategoryName = "Diabetes Care"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryDescription = "Cardiovascular health support products",
                            CategoryName = "Heart Health"
                        });
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.Discount.CategoryDiscountModel", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<Guid>("DiscountId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoryId", "DiscountId");

                    b.HasIndex("DiscountId");

                    b.ToTable("CategoryDiscounts");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.Discount.DiscountModel", b =>
                {
                    b.Property<Guid>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaximumOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("DiscountId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Discount_IsActive");

                    b.HasIndex("IsActive", "StartDate", "EndDate")
                        .HasDatabaseName("IX_Discount_Active_Dates");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.Discount.ProductDiscountModel", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<Guid>("DiscountId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "DiscountId");

                    b.HasIndex("DiscountId");

                    b.ToTable("ProductDiscounts");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.OrderAddressModel", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("AddressId");

                    b.ToTable("OrderAddresses");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.OrderItemModel", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AppliedDiscountId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.OrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppliedPromoCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("BonusPointsEarned")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BonusPointsRedeemed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("PromoCodeDiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid?>("PromoCodeId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("ShippingAddressId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubtotalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "High-potency vitamin C tablets for immune support. Take 1 tablet daily with food.",
                            ImageUrl = "https://via.placeholder.com/400/FF6B6B/FFFFFF?text=Vitamin+C",
                            Name = "Vitamin C 1000mg",
                            Price = 15.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Essential vitamin D for bone health and immune function. Supports calcium absorption.",
                            ImageUrl = "https://via.placeholder.com/400/4ECDC4/FFFFFF?text=Vitamin+D3",
                            Name = "Vitamin D3 5000 IU",
                            Price = 18.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Daily multivitamin with essential nutrients for overall health and wellness.",
                            ImageUrl = "https://via.placeholder.com/400/95E1D3/FFFFFF?text=Multivitamin",
                            Name = "Multivitamin Complex",
                            Price = 24.99m,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "High-quality omega-3 fatty acids for heart and brain health.",
                            ImageUrl = "https://via.placeholder.com/400/F38181/FFFFFF?text=Omega-3",
                            Name = "Omega-3 Fish Oil 1200mg",
                            Price = 29.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Bone support formula with vitamin D3 for optimal absorption.",
                            ImageUrl = "https://via.placeholder.com/400/AA96DA/FFFFFF?text=Calcium",
                            Name = "Calcium + Magnesium",
                            Price = 19.99m,
                            StockQuantity = 160
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Immune system support and wound healing. Antioxidant properties.",
                            ImageUrl = "https://via.placeholder.com/400/FCBAD3/FFFFFF?text=Zinc",
                            Name = "Zinc 50mg",
                            Price = 12.99m,
                            StockQuantity = 220
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Gentle iron formula for energy and red blood cell production.",
                            ImageUrl = "https://via.placeholder.com/400/FFFFD2/000000?text=Iron",
                            Name = "Iron Supplement 65mg",
                            Price = 14.99m,
                            StockQuantity = 140
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Energy and metabolism support with all 8 B vitamins.",
                            ImageUrl = "https://via.placeholder.com/400/A8D8EA/FFFFFF?text=B-Complex",
                            Name = "B-Complex Vitamins",
                            Price = 16.99m,
                            StockQuantity = 190
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Digestive health support with 10 probiotic strains. Refrigerated formula.",
                            ImageUrl = "https://via.placeholder.com/400/FFAAA5/FFFFFF?text=Probiotics",
                            Name = "Probiotics 10 Billion CFU",
                            Price = 32.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Joint health support for flexibility and mobility.",
                            ImageUrl = "https://via.placeholder.com/400/FF8B94/FFFFFF?text=Glucosamine",
                            Name = "Glucosamine Chondroitin MSM",
                            Price = 34.99m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Fast-acting pain and fever relief. Anti-inflammatory properties.",
                            ImageUrl = "https://via.placeholder.com/400/FFA07A/FFFFFF?text=Ibuprofen",
                            Name = "Ibuprofen 400mg",
                            Price = 8.99m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Pain relief and blood thinner. Reduces risk of heart attack.",
                            ImageUrl = "https://via.placeholder.com/400/98D8C8/FFFFFF?text=Aspirin",
                            Name = "Aspirin 500mg",
                            Price = 6.99m,
                            StockQuantity = 350
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Effective pain and fever relief. Gentle on stomach.",
                            ImageUrl = "https://via.placeholder.com/400/F7B731/FFFFFF?text=Paracetamol",
                            Name = "Paracetamol 500mg",
                            Price = 7.99m,
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Long-lasting pain relief up to 12 hours.",
                            ImageUrl = "https://via.placeholder.com/400/5F27CD/FFFFFF?text=Naproxen",
                            Name = "Naproxen 250mg",
                            Price = 11.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Topical pain relief for muscles and joints. Fast absorption.",
                            ImageUrl = "https://via.placeholder.com/400/00D2FF/FFFFFF?text=Pain+Gel",
                            Name = "Muscle Pain Relief Gel",
                            Price = 13.99m,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "Multi-symptom cold relief. Daytime and nighttime formulas.",
                            ImageUrl = "https://via.placeholder.com/400/1E90FF/FFFFFF?text=Cold+Relief",
                            Name = "Cold & Flu Relief Day & Night",
                            Price = 12.99m,
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "Soothes cough and throat irritation. Non-drowsy formula.",
                            ImageUrl = "https://via.placeholder.com/400/ED4C67/FFFFFF?text=Cough+Syrup",
                            Name = "Cough Syrup",
                            Price = 10.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "Soothing throat relief with menthol and honey.",
                            ImageUrl = "https://via.placeholder.com/400/B33771/FFFFFF?text=Lozenges",
                            Name = "Throat Lozenges",
                            Price = 5.99m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Description = "Fast nasal congestion relief. Works in minutes.",
                            ImageUrl = "https://via.placeholder.com/400/3B3B98/FFFFFF?text=Nasal+Spray",
                            Name = "Nasal Decongestant Spray",
                            Price = 9.99m,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Assorted sizes bandages. Flexible and breathable.",
                            ImageUrl = "https://via.placeholder.com/400/26de81/FFFFFF?text=Bandages",
                            Name = "Adhesive Bandages 100pk",
                            Price = 6.99m,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "Medical grade gauze for wound care. Highly absorbent.",
                            ImageUrl = "https://via.placeholder.com/400/20bf6b/FFFFFF?text=Gauze",
                            Name = "Sterile Gauze Pads",
                            Price = 8.99m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "Wound cleansing solution. Prevents infection.",
                            ImageUrl = "https://via.placeholder.com/400/45aaf2/FFFFFF?text=Antiseptic",
                            Name = "Antiseptic Solution 500ml",
                            Price = 7.99m,
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "Complete first aid kit with 100+ items for home or travel.",
                            ImageUrl = "https://via.placeholder.com/400/ff9ff3/000000?text=First+Aid+Kit",
                            Name = "First Aid Kit Deluxe",
                            Price = 34.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Description = "Deep hydration for all skin types. Non-greasy formula.",
                            ImageUrl = "https://via.placeholder.com/400/feca57/000000?text=Moisturizer",
                            Name = "Moisturizing Cream",
                            Price = 16.99m,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Description = "Clears acne and prevents breakouts. Contains benzoyl peroxide.",
                            ImageUrl = "https://via.placeholder.com/400/48dbfb/FFFFFF?text=Acne+Gel",
                            Name = "Acne Treatment Gel",
                            Price = 19.99m,
                            StockQuantity = 140
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            Description = "Broad spectrum sun protection. Water resistant 80 minutes.",
                            ImageUrl = "https://via.placeholder.com/400/ff9ff3/FFFFFF?text=Sunscreen",
                            Name = "Sunscreen SPF 50+",
                            Price = 14.99m,
                            StockQuantity = 220
                        });
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.PromoCode.PromoCodeCategoryModel", b =>
                {
                    b.Property<Guid>("PromoCodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.HasKey("PromoCodeId", "CategoryId");

                    b.ToTable("PromoCodeCategories");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.PromoCode.PromoCodeModel", b =>
                {
                    b.Property<Guid>("PromoCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ApplicableToAllProducts")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CurrentUsageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxUsageCount")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxUsagePerUser")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaximumDiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("PromoCodeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.PromoCode.PromoCodeProductModel", b =>
                {
                    b.Property<Guid>("PromoCodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("PromoCodeId", "ProductId");

                    b.ToTable("PromoCodeProducts");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.PromoCode.PromoCodeUsageModel", b =>
                {
                    b.Property<Guid>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountApplied")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<Guid>("PromoCodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsageId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PromoCodeId", "UserId");

                    b.ToTable("PromoCodeUsages");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.RefreshTokenModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.ReviewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.ShoppingCartModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasFilter("\"SessionId\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("ShoppingCart", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShoppingCart_UserOrSession", "\"UserId\" IS NOT NULL OR \"SessionId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.UserAddressModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsDefault");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsPasswordReset")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.WishlistModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyApp.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.Bonus.BonusAccountModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.UserModel", "User")
                        .WithOne("BonusAccount")
                        .HasForeignKey("PharmacyApp.Domain.Entities.Bonus.BonusAccountModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.Bonus.BonusTransactionModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.Bonus.BonusAccountModel", "BonusAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("BonusAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonusAccount");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.CartItemModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.ShoppingCartModel", "ShoppingCart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyApp.Domain.Entities.ProductModel", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.Discount.CategoryDiscountModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.CategoryModel", "Category")
                        .WithMany("CategoryDiscounts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyApp.Domain.Entities.Discount.DiscountModel", "Discount")
                        .WithMany("CategoryDiscounts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.Discount.ProductDiscountModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.Discount.DiscountModel", "Discount")
                        .WithMany("ProductDiscounts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyApp.Domain.Entities.ProductModel", "Product")
                        .WithMany("ProductDiscounts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.OrderItemModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.OrderModel", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyApp.Domain.Entities.ProductModel", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.OrderModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.OrderAddressModel", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyApp.Domain.Entities.UserModel", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.ProductModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.CategoryModel", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.PromoCode.PromoCodeCategoryModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.PromoCode.PromoCodeModel", "PromoCode")
                        .WithMany("PromoCodeCategories")
                        .HasForeignKey("PromoCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromoCode");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.PromoCode.PromoCodeProductModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.PromoCode.PromoCodeModel", "PromoCode")
                        .WithMany("PromoCodeProducts")
                        .HasForeignKey("PromoCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromoCode");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.PromoCode.PromoCodeUsageModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.PromoCode.PromoCodeModel", "PromoCode")
                        .WithMany("UsageHistory")
                        .HasForeignKey("PromoCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromoCode");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.RefreshTokenModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.UserModel", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.ReviewModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.ProductModel", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacyApp.Domain.Entities.UserModel", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.ShoppingCartModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.UserAddressModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.UserModel", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.WishlistModel", b =>
                {
                    b.HasOne("PharmacyApp.Domain.Entities.ProductModel", "Product")
                        .WithMany("Wishlist")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyApp.Domain.Entities.UserModel", "User")
                        .WithMany("Wishlist")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.Bonus.BonusAccountModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.CategoryModel", b =>
                {
                    b.Navigation("CategoryDiscounts");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.Discount.DiscountModel", b =>
                {
                    b.Navigation("CategoryDiscounts");

                    b.Navigation("ProductDiscounts");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.OrderModel", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.ProductModel", b =>
                {
                    b.Navigation("ProductDiscounts");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.PromoCode.PromoCodeModel", b =>
                {
                    b.Navigation("PromoCodeCategories");

                    b.Navigation("PromoCodeProducts");

                    b.Navigation("UsageHistory");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.ShoppingCartModel", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PharmacyApp.Domain.Entities.UserModel", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("BonusAccount");

                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
